App-sre migration from saas-analytics
fabric8-analytics/fabric8-analytics-license-analysis pull request #224
Opened 2021-03-26 09:08 UTC by deepak1725

# Description

App-sre migration from saas-analytics

Fixes # (issue)
https://issues.redhat.com/browse/APPAI-1810

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2021-03-26 09:16 UTC, prashbnair requested changes

2021-03-26 09:16 UTC, prashbnair commented on Dockerfile.app-sre
> +FROM quay.io/app-sre/fabric8-analytics-f8a-license-analysis
Can you not use ubi images?

2021-03-26 09:16 UTC, prashbnair commented on Dockerfile.app-sre
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-auth.git@${F8A_AUTH_VERSION}
is this not handled in requirements.txt

2021-03-26 09:20 UTC, deepak1725 commented on Dockerfile.app-sre
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-auth.git@${F8A_AUTH_VERSION}
This is an exact copy of the existing Docker file, did modifications in base image only

2021-03-26 09:23 UTC, deepak1725 commented on Dockerfile.app-sre
> +FROM quay.io/app-sre/fabric8-analytics-f8a-license-analysis
i thought image names should match with what we gave in SRE, https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/15370/diffs

2021-03-26 10:32 UTC, sawood14012 requested changes

2021-03-26 10:32 UTC, sawood14012 commented on build_deploy.rhel.sh
> +              -f ./Dockerfile .
this should build your rhel docker file that is `Dockerfile.rhel.app-sre`

2021-03-26 10:32 UTC, sawood14012 commented on build_deploy.sh
> +              -f ./Dockerfile .
similar way here `Dockerfile.app-sre`

2021-03-26 10:32 UTC, sawood14012 commented on Dockerfile.rhel.app-sre
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-auth.git@${F8A_AUTH_VERSION}
please include auth in` requirements.txt `

2021-03-26 11:14 UTC, prashbnair commented on Dockerfile.app-sre
> +FROM quay.io/app-sre/fabric8-analytics-f8a-license-analysis
You should move to UBI images and get rid of the RHEL build.
https://github.com/fabric8-analytics/f8a-stacks-report/blob/master/Dockerfile.new

2021-03-26 11:21 UTC, deepak1725 commented on build_deploy.rhel.sh
> +              -f ./Dockerfile .
Ack

2021-03-26 11:21 UTC, deepak1725 commented on build_deploy.sh
> +              -f ./Dockerfile .
Ack.

2021-03-26 11:28 UTC, deepak1725 commented on Dockerfile.app-sre
> +FROM quay.io/app-sre/fabric8-analytics-f8a-license-analysis
Ack

2021-03-26 11:33 UTC, prashbnair requested changes

2021-03-26 11:33 UTC, prashbnair commented on Dockerfile.new
> +ENV F8A_AUTH_VERSION=fff8f49
Line repeated

2021-03-26 11:33 UTC, prashbnair commented on Dockerfile.new
> +RUN pip3 install -r requirements.txt && rm requirements.txt
--no-cache is required to reduce image size.

2021-03-26 11:33 UTC, prashbnair commented on Dockerfile.new
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-auth.git@${F8A_AUTH_VERSION}
Can you move this to requirements.in?

2021-03-26 12:15 UTC, deepak1725 commented on Dockerfile.new
> +ENV F8A_AUTH_VERSION=fff8f49
removed

2021-03-26 12:15 UTC, deepak1725 commented on Dockerfile.new
> +RUN pip3 install -r requirements.txt && rm requirements.txt
Ack.

2021-03-26 12:15 UTC, deepak1725 commented on Dockerfile.new
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-auth.git@${F8A_AUTH_VERSION}
done

2021-03-26 13:08 UTC, prashbnair commented on Dockerfile.new
> +RUN yum install -y epel-release && \
Have you tested this, I dont think ubi-minimal has yum, you have to use microdnf.

2021-03-26 13:09 UTC, prashbnair commented on Dockerfile.new
> +RUN pip3 install -r requirements.txt && rm requirements.txt --no-cache
Can you also check if it --no-cache or --no-cache-dir?

2021-03-29 06:15 UTC, deepak1725 commented on Dockerfile.rhel.app-sre
> +RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-auth.git@${F8A_AUTH_VERSION}
Ack

2021-03-29 06:16 UTC, deepak1725 commented on Dockerfile.new
> +RUN yum install -y epel-release && \
done, Updated image with ubi-minimal

2021-03-29 06:16 UTC, deepak1725 commented on Dockerfile.new
> +RUN pip3 install -r requirements.txt && rm requirements.txt --no-cache
yup, its `--no-cache-dir` Updated

2021-03-29 08:29 UTC, prashbnair approved these changes

2021-03-29 09:04 UTC, sawood14012 approved these changes

2021-03-29 09:09 UTC, merged